runtime: nodejs12
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$   #https://calculadora-demo.ue.r.appspot.com/
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html